package dev.unzor.Deprecated;

import dev.unzor.Util.GeneralUtil;

import java.awt.Color;

/**
 *
 * @author marco
 */
public class GUI_old extends javax.swing.JFrame {

    int xMouse, yMouse;

    /**
     * Creates new form GUI
     */
    public GUI_old() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        BackgroundPanel = new javax.swing.JPanel();
        ButtonHolderPanel = new javax.swing.JPanel();
        Button1 = new javax.swing.JPanel();
        Button1Label = new javax.swing.JLabel();
        Button2 = new javax.swing.JPanel();
        Button2Label = new javax.swing.JLabel();
        Button3 = new javax.swing.JPanel();
        Button3Label = new javax.swing.JLabel();
        Button4 = new javax.swing.JPanel();
        Button4Label = new javax.swing.JLabel();
        Button5 = new javax.swing.JPanel();
        Button5Label = new javax.swing.JLabel();
        Button6 = new javax.swing.JPanel();
        Button6Label = new javax.swing.JLabel();
        Button7 = new javax.swing.JPanel();
        Button7Label = new javax.swing.JLabel();
        ButtonHolderPanel2 = new javax.swing.JPanel();
        Button8 = new javax.swing.JPanel();
        Button8Label = new javax.swing.JLabel();
        Button9 = new javax.swing.JPanel();
        Button9Label = new javax.swing.JLabel();
        Button10 = new javax.swing.JPanel();
        Button10Label = new javax.swing.JLabel();
        Button11 = new javax.swing.JPanel();
        Button11Label = new javax.swing.JLabel();
        Button12 = new javax.swing.JPanel();
        Button12Label = new javax.swing.JLabel();
        Button13 = new javax.swing.JPanel();
        Button13Label = new javax.swing.JLabel();
        Button14 = new javax.swing.JPanel();
        Button14Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        materialComboBox = new javax.swing.JComboBox<>();
        tierComboBox = new javax.swing.JComboBox<>();
        overclockComboBox = new javax.swing.JComboBox<>();
        cantidadSpinner = new javax.swing.JSpinner();
        addToTableButton = new javax.swing.JButton();
        deleteFromTableButton = new javax.swing.JButton();
        juntarRepeticionesButton = new javax.swing.JButton();
        materialLabel = new javax.swing.JLabel();
        cantidadLabel = new javax.swing.JLabel();
        tierLabel = new javax.swing.JLabel();
        scrollpaneltablamenas = new javax.swing.JScrollPane();
        tablaMenas = new javax.swing.JTable();
        overclockLabel = new javax.swing.JLabel();
        cantidadporminutoLabel = new javax.swing.JLabel();
        cantidadporminutoSpinner = new javax.swing.JSpinner();
        calcularPanel = new javax.swing.JPanel();
        calcularLabel = new javax.swing.JLabel();
        TitleLabel = new javax.swing.JLabel();
        utilitybarPanel = new javax.swing.JPanel();
        closePanel = new javax.swing.JPanel();
        XLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setResizable(false);

        BackgroundPanel.setBackground(new java.awt.Color(54, 57, 63));

        ButtonHolderPanel.setBackground(new java.awt.Color(54, 57, 63));

        Button1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button1Label.setText("PLACEHOLDER 1");
        Button1Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Button1Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button1LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button1LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button1LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button1Layout = new javax.swing.GroupLayout(Button1);
        Button1.setLayout(Button1Layout);
        Button1Layout.setHorizontalGroup(
                Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button1Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button1Layout.setVerticalGroup(
                Button1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button1Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button2Label.setText("PLACEHOLDER 2");
        Button2Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button2Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button2LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button2LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button2LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button2Layout = new javax.swing.GroupLayout(Button2);
        Button2.setLayout(Button2Layout);
        Button2Layout.setHorizontalGroup(
                Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button2Label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button2Layout.setVerticalGroup(
                Button2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button2Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button3Label.setText("PLACEHOLDER 3");
        Button3Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button3Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button3LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button3LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button3LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button3Layout = new javax.swing.GroupLayout(Button3);
        Button3.setLayout(Button3Layout);
        Button3Layout.setHorizontalGroup(
                Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button3Layout.setVerticalGroup(
                Button3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button3Label, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        Button4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button4Label.setText("PLACEHOLDER 4");
        Button4Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button4Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button4LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button4LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button4LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button4Layout = new javax.swing.GroupLayout(Button4);
        Button4.setLayout(Button4Layout);
        Button4Layout.setHorizontalGroup(
                Button4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button4Layout.setVerticalGroup(
                Button4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button4Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button5Label.setText("PLACEHOLDER 5");
        Button5Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button5Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button5LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button5LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button5LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button5Layout = new javax.swing.GroupLayout(Button5);
        Button5.setLayout(Button5Layout);
        Button5Layout.setHorizontalGroup(
                Button5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button5Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button5Layout.setVerticalGroup(
                Button5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button5Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button6Label.setText("PLACEHOLDER 6");
        Button6Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button6Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button6LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button6LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button6LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button6Layout = new javax.swing.GroupLayout(Button6);
        Button6.setLayout(Button6Layout);
        Button6Layout.setHorizontalGroup(
                Button6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button6Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button6Layout.setVerticalGroup(
                Button6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button6Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button7Label.setText("PLACEHOLDER 7");
        Button7Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button7Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button7LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button7LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button7LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button7Layout = new javax.swing.GroupLayout(Button7);
        Button7.setLayout(Button7Layout);
        Button7Layout.setHorizontalGroup(
                Button7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button7Label, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
        Button7Layout.setVerticalGroup(
                Button7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button7Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ButtonHolderPanelLayout = new javax.swing.GroupLayout(ButtonHolderPanel);
        ButtonHolderPanel.setLayout(ButtonHolderPanelLayout);
        ButtonHolderPanelLayout.setHorizontalGroup(
                ButtonHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonHolderPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ButtonHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Button7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        ButtonHolderPanelLayout.setVerticalGroup(
                ButtonHolderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonHolderPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(Button1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Button7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(68, Short.MAX_VALUE))
        );

        ButtonHolderPanel2.setBackground(new java.awt.Color(54, 57, 63));

        Button8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button8Label.setText("PLACEHOLDER 8");
        Button8Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button8Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button8LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button8LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button8LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button8Layout = new javax.swing.GroupLayout(Button8);
        Button8.setLayout(Button8Layout);
        Button8Layout.setHorizontalGroup(
                Button8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button8Label, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
        );
        Button8Layout.setVerticalGroup(
                Button8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button8Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button9Label.setText("PLACEHOLDER 9");
        Button9Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button9Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button9LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button9LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button9LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button9Layout = new javax.swing.GroupLayout(Button9);
        Button9.setLayout(Button9Layout);
        Button9Layout.setHorizontalGroup(
                Button9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button9Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button9Layout.setVerticalGroup(
                Button9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button9Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button10Label.setText("PLACEHOLDER 10");
        Button10Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button10Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button10LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button10LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button10LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button10Layout = new javax.swing.GroupLayout(Button10);
        Button10.setLayout(Button10Layout);
        Button10Layout.setHorizontalGroup(
                Button10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button10Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button10Layout.setVerticalGroup(
                Button10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button10Label, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        Button11Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button11Label.setText("PLACEHOLDER 11");
        Button11Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button11Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button11LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button11LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button11LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button11Layout = new javax.swing.GroupLayout(Button11);
        Button11.setLayout(Button11Layout);
        Button11Layout.setHorizontalGroup(
                Button11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button11Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button11Layout.setVerticalGroup(
                Button11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button11Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button12Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button12Label.setText("PLACEHOLDER 12");
        Button12Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button12Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button12LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button12LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button12LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button12Layout = new javax.swing.GroupLayout(Button12);
        Button12.setLayout(Button12Layout);
        Button12Layout.setHorizontalGroup(
                Button12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button12Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button12Layout.setVerticalGroup(
                Button12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button12Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button13Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button13Label.setText("PLACEHOLDER 13");
        Button13Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button13Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button13LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button13LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button13LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button13Layout = new javax.swing.GroupLayout(Button13);
        Button13.setLayout(Button13Layout);
        Button13Layout.setHorizontalGroup(
                Button13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button13Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button13Layout.setVerticalGroup(
                Button13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button13Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        Button14Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Button14Label.setText("PLACEHOLDER 14");
        Button14Label.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Button14Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button14LabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Button14LabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Button14LabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Button14Layout = new javax.swing.GroupLayout(Button14);
        Button14.setLayout(Button14Layout);
        Button14Layout.setHorizontalGroup(
                Button14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button14Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        Button14Layout.setVerticalGroup(
                Button14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Button14Label, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(54, 57, 63));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Menas");

        materialComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mena 1", "Mena 2"}));

        tierComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pura", "Normal", "Impura"}));

        overclockComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin overclock", "1 overclock", "2 overclock", "3 overclock"}));
        overclockComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overclockComboBoxActionPerformed(evt);
            }
        });

        addToTableButton.setText("Añadir");
        addToTableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addToTableButtonMouseClicked(evt);
            }
        });

        deleteFromTableButton.setText("Eliminar");
        deleteFromTableButton.addMouseListener(new java.awt.event.MouseAdapter() {
        });
        deleteFromTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteFromTableButtonActionPerformed(evt);
            }
        });

        juntarRepeticionesButton.setText("Juntar repeticiones");
        juntarRepeticionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                juntarRepeticionesButtonActionPerformed(evt);
            }
        });

        materialLabel.setForeground(new java.awt.Color(255, 255, 255));
        materialLabel.setText("Material");

        cantidadLabel.setForeground(new java.awt.Color(255, 255, 255));
        cantidadLabel.setText("Cantidad");

        tierLabel.setForeground(new java.awt.Color(255, 255, 255));
        tierLabel.setText("Tier");

        tablaMenas.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "Material", "Cantidad", "Tier", "Overclock"
                }
        ));
        tablaMenas.setShowGrid(true);
        scrollpaneltablamenas.setViewportView(tablaMenas);

        overclockLabel.setForeground(new java.awt.Color(255, 255, 255));
        overclockLabel.setText("Nivel de overclock");

        cantidadporminutoLabel.setForeground(new java.awt.Color(255, 255, 255));
        cantidadporminutoLabel.setText("Cantidad por minuto");

        calcularLabel.setFont(new java.awt.Font("Roboto", 1, 32)); // NOI18N
        calcularLabel.setLabelFor(calcularPanel);
        calcularLabel.setText("CALCULAR");
        calcularLabel.setToolTipText("");
        calcularLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        calcularLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        calcularLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calcularLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                calcularLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                calcularLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout calcularPanelLayout = new javax.swing.GroupLayout(calcularPanel);
        calcularPanel.setLayout(calcularPanelLayout);
        calcularPanelLayout.setHorizontalGroup(
                calcularPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(calcularLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
        );
        calcularPanelLayout.setVerticalGroup(
                calcularPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(calcularLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(scrollpaneltablamenas)
                                                .addContainerGap())
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(materialLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(cantidadLabel))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(tierLabel)
                                                                        .addComponent(tierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addComponent(cantidadporminutoLabel)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(cantidadporminutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(overclockLabel)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(overclockComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(addToTableButton)))
                                                                .addGap(64, 64, 64))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addComponent(juntarRepeticionesButton)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(deleteFromTableButton)
                                                                .addContainerGap())))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(167, 167, 167)
                                .addComponent(calcularPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(materialComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tierComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(addToTableButton)
                                                        .addComponent(overclockComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(cantidadSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(cantidadLabel)
                                                .addComponent(tierLabel)
                                                .addComponent(materialLabel)
                                                .addComponent(overclockLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scrollpaneltablamenas, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(cantidadporminutoLabel)
                                        .addComponent(cantidadporminutoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(deleteFromTableButton)
                                        .addComponent(juntarRepeticionesButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(calcularPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ButtonHolderPanel2Layout = new javax.swing.GroupLayout(ButtonHolderPanel2);
        ButtonHolderPanel2.setLayout(ButtonHolderPanel2Layout);
        ButtonHolderPanel2Layout.setHorizontalGroup(
                ButtonHolderPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonHolderPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ButtonHolderPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Button14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonHolderPanel2Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(Button9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Button12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(41, 41, 41)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        ButtonHolderPanel2Layout.setVerticalGroup(
                ButtonHolderPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ButtonHolderPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(ButtonHolderPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(ButtonHolderPanel2Layout.createSequentialGroup()
                                                .addComponent(Button8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Button9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Button10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Button11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Button12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Button13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(Button14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(72, Short.MAX_VALUE))
        );

        TitleLabel.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Satisfactory Crafter");

        utilitybarPanel.setBackground(new java.awt.Color(54, 57, 63));
        utilitybarPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                utilitybarPanelMouseDragged(evt);
            }
        });
        utilitybarPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                utilitybarPanelMousePressed(evt);
            }
        });

        closePanel.setBackground(new java.awt.Color(54, 57, 63));

        XLabel.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        XLabel.setForeground(new java.awt.Color(255, 255, 255));
        XLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        XLabel.setText("X");
        XLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        XLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                XLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                XLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                XLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closePanelLayout = new javax.swing.GroupLayout(closePanel);
        closePanel.setLayout(closePanelLayout);
        closePanelLayout.setHorizontalGroup(
                closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(XLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        closePanelLayout.setVerticalGroup(
                closePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(XLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout utilitybarPanelLayout = new javax.swing.GroupLayout(utilitybarPanel);
        utilitybarPanel.setLayout(utilitybarPanelLayout);
        utilitybarPanelLayout.setHorizontalGroup(
                utilitybarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(utilitybarPanelLayout.createSequentialGroup()
                                .addComponent(closePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        utilitybarPanelLayout.setVerticalGroup(
                utilitybarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(utilitybarPanelLayout.createSequentialGroup()
                                .addComponent(closePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundPanelLayout = new javax.swing.GroupLayout(BackgroundPanel);
        BackgroundPanel.setLayout(BackgroundPanelLayout);
        BackgroundPanelLayout.setHorizontalGroup(
                BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(ButtonHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ButtonHolderPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(47, Short.MAX_VALUE))
                        .addComponent(utilitybarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        BackgroundPanelLayout.setVerticalGroup(
                BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BackgroundPanelLayout.createSequentialGroup()
                                .addComponent(utilitybarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(BackgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ButtonHolderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ButtonHolderPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(BackgroundPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>                        

    private void overclockComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void XLabelMouseEntered(java.awt.event.MouseEvent evt) {
        closePanel.setBackground(Color.red);
        XLabel.setForeground(Color.white);
    }

    private void XLabelMouseExited(java.awt.event.MouseEvent evt) {
        Color background = new Color(54,57,63);

        closePanel.setBackground(background);
        XLabel.setForeground(Color.white);
    }

    private void XLabelMouseClicked(java.awt.event.MouseEvent evt) {
        System.exit(0);
    }

    private void utilitybarPanelMousePressed(java.awt.event.MouseEvent evt) {
        xMouse = evt.getX();
        yMouse = evt.getY();
    }

    private void utilitybarPanelMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }

    private void Button1LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button1LabelMouseEntered(java.awt.event.MouseEvent evt) {
        Color naranjaoscuro = new Color(231, 71, 27);

        Button1.setBackground(naranjaoscuro);
    }

    private void Button1LabelMouseExited(java.awt.event.MouseEvent evt) {
        Color naranja = new Color(228, 114, 81);

        Button1.setBackground(naranja);
    }

    private void Button2LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button2LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button2LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button3LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button3LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button3LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button4LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button4LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button4LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button5LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button5LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button5LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button6LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button6LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button6LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button7LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button7LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button7LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button8LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button8LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button8LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button9LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button9LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button9LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button10LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button10LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button10LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button11LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button11LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button11LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button12LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button12LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button12LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button13LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button13LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button13LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button14LabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button14LabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void Button14LabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void addToTableButtonMouseClicked(java.awt.event.MouseEvent evt) {
        GeneralUtil.printDebug("Material: " + materialComboBox.getSelectedItem());
        GeneralUtil.printDebug("Cantidad: " + cantidadSpinner.getValue());
        GeneralUtil.printDebug("Tier: " + tierComboBox.getSelectedItem());
        GeneralUtil.printDebug("Cantidad de overclock: " + overclockComboBox.getSelectedItem());

        GeneralUtil.addStuffToTable(tablaMenas ,materialComboBox.getSelectedItem().toString(), cantidadSpinner.getValue().toString(), tierComboBox.getSelectedItem().toString(), overclockComboBox.getSelectedItem().toString());
        GeneralUtil.printTableContent(tablaMenas, 1);
    }

    private void calcularLabelMouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void calcularLabelMouseEntered(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void calcularLabelMouseExited(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
    }

    private void deleteFromTableButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void juntarRepeticionesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        System.out.println("Juntar repeticiones");
        GeneralUtil.compareTableContent(tablaMenas);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_old().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JPanel Button1;
    private javax.swing.JPanel Button10;
    private javax.swing.JLabel Button10Label;
    private javax.swing.JPanel Button11;
    private javax.swing.JLabel Button11Label;
    private javax.swing.JPanel Button12;
    private javax.swing.JLabel Button12Label;
    private javax.swing.JPanel Button13;
    private javax.swing.JLabel Button13Label;
    private javax.swing.JPanel Button14;
    private javax.swing.JLabel Button14Label;
    private javax.swing.JLabel Button1Label;
    private javax.swing.JPanel Button2;
    private javax.swing.JLabel Button2Label;
    private javax.swing.JPanel Button3;
    private javax.swing.JLabel Button3Label;
    private javax.swing.JPanel Button4;
    private javax.swing.JLabel Button4Label;
    private javax.swing.JPanel Button5;
    private javax.swing.JLabel Button5Label;
    private javax.swing.JPanel Button6;
    private javax.swing.JLabel Button6Label;
    private javax.swing.JPanel Button7;
    private javax.swing.JLabel Button7Label;
    private javax.swing.JPanel Button8;
    private javax.swing.JLabel Button8Label;
    private javax.swing.JPanel Button9;
    private javax.swing.JLabel Button9Label;
    private javax.swing.JPanel ButtonHolderPanel;
    private javax.swing.JPanel ButtonHolderPanel2;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JLabel XLabel;
    private javax.swing.JButton addToTableButton;
    private javax.swing.JButton juntarRepeticionesButton;
    private javax.swing.JLabel calcularLabel;
    private javax.swing.JPanel calcularPanel;
    private javax.swing.JLabel cantidadLabel;
    private javax.swing.JSpinner cantidadSpinner;
    private javax.swing.JLabel cantidadporminutoLabel;
    private javax.swing.JSpinner cantidadporminutoSpinner;
    private javax.swing.JPanel closePanel;
    private javax.swing.JButton deleteFromTableButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JComboBox<String> materialComboBox;
    private javax.swing.JLabel materialLabel;
    private javax.swing.JComboBox<String> overclockComboBox;
    private javax.swing.JLabel overclockLabel;
    private javax.swing.JScrollPane scrollpaneltablamenas;
    private javax.swing.JTable tablaMenas;
    private javax.swing.JComboBox<String> tierComboBox;
    private javax.swing.JLabel tierLabel;
    private javax.swing.JPanel utilitybarPanel;
    // End of variables declaration                   
}